FROM oven/bun:1-alpine AS base
WORKDIR /app


FROM base AS build

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

ADD . ./

ARG VITE_APP_GIT_SHA=unknown
ARG VITE_APP_GIT_TIMESTAMP=1970-01-01T00:00:00Z
ARG VITE_COMMA_URL_ROOT=https://api.comma.ai/
ARG VITE_ATHENA_URL_ROOT=https://athena.comma.ai/
ARG VITE_BILLING_URL_ROOT=https://billing.comma.ai/
ARG VITE_USERADMIN_URL_ROOT=https://useradmin.comma.ai/
ARG VITE_REFERRAL_URL=https://refer.comma.ai/
ARG VITE_SENTRY_ENV
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_RELEASE
ENV VITE_APP_GIT_SHA=$VITE_APP_GIT_SHA \
    VITE_APP_GIT_TIMESTAMP=$VITE_APP_GIT_TIMESTAMP \
    VITE_COMMA_URL_ROOT=$VITE_COMMA_URL_ROOT \
    VITE_ATHENA_URL_ROOT=$VITE_ATHENA_URL_ROOT \
    VITE_BILLING_URL_ROOT=$VITE_BILLING_URL_ROOT \
    VITE_USERADMIN_URL_ROOT=$VITE_USERADMIN_URL_ROOT \
    VITE_REFERRAL_URL=$VITE_REFERRAL_URL \
    VITE_SENTRY_ENV=$VITE_SENTRY_ENV \
    SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
    SENTRY_RELEASE=$SENTRY_RELEASE

RUN bun run build:production


FROM nginx:1.24-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
