// init
export const ACTION_STARTUP_DATA = 'ACTION_STARTUP_DATA';

// global state management
export const ACTION_PROFILE_REFRESHED = 'ACTION_PROFILE_REFRESHED';
export const ACTION_SELECT_DEVICE = 'ACTION_SELECT_DEVICE';
export const ACTION_SELECT_TIME_RANGE = 'ACTION_SELECT_TIME_RANGE';
export const ACTION_UPDATE_DEVICE = 'ACTION_UPDATE_DEVICE';
