name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun playwright install
      - run: bun run lint --reporter=github
      - run: bun run test
      - run: bun lines

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun run build
        env:
          VITE_SENTRY_ENVIRONMENT: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}

      - name: Bundle size breakdown
        run: bun dependency-report | column -t -s ":"
      - run: bun bundle-size

      - name: Upload built project
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          overwrite: true
          retention-days: 1
          name: build-artifacts-${{ github.run_id }}

      - run: bun .github/actions/combine_artifacts.ts

      - name: Deploy to Cloudflare Pages
        if: github.ref == 'refs/heads/master' && github.repository == 'commaai/new-connect'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          command: pages deploy dist --project-name=connect --branch=new-connect --commit-dirty=true
