name: Deploy to Cloudflare Pages

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: |
      github.event.repository.full_name == 'commaai/connect' && (
        github.event_name == 'pull_request' ||
        github.event.pull_request.head.repo.full_name == 'commaai/connect'
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and PNPM
        uses: commaai/setup-pnpm@v1
        with:
          node-version: '16'
          pnpm-version: '8'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build:production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/cloudflare-pages-action@v1.5.0
        with:
          api_token: ${{ secrets.CF_API_TOKEN }}
          build_dir: dist

      - name: Comment URL on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Deploy Preview: ${{ steps.cloudflare-publish.outputs.url }}'

