name: preview

on:
  pull_request:

jobs:
  preview:
    if: |
      github.event.repository.full_name == 'commaai/connect' && (
        github.event_name == 'pull_request' ||
        github.event.pull_request.head.repo.full_name == 'commaai/connect'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PNPM
        uses: ./.github/actions/setup-pnpm/
        with:
          node-version: '16'
          pnpm-version: '8'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: npm run build:production
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          directory: dist
      - name: Comment URL on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Deploy Preview: ${{ steps.cloudflare-publish.outputs.url }}'
